### ISSUE TITLE
Fresh installation using pip not working

### ISSUE THREAD

**Issue by kobuki** [adameste/anidbcli#3]
```
~# pip install anidbcli
Collecting anidbcli
Collecting pyperclip (from anidbcli)
  Using cached https://files.pythonhosted.org/packages/2d/9a/23059a00dfd52eb700bd03c4ee3a6954cae60827539c3488026c8742a555/pyperclip-1.6.4.tar.gz
Collecting colorama (from anidbcli)
  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Collecting click (from anidbcli)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting joblib (from anidbcli)
  Using cached https://files.pythonhosted.org/packages/f6/26/317725ffd9e8e8c0eb4b2fc77614f52045ddfc1c5026387fbefef9050eec/joblib-0.12.2-py2.py3-none-any.whl
Collecting pycryptodome (from anidbcli)
  Using cached https://files.pythonhosted.org/packages/40/26/1546cda8b55c08001c9100c031bd1be4c93edb18bee788877f7e23fc1ecd/pycryptodome-3.6.6-cp27-cp27mu-manylinux1_x86_64.whl
Building wheels for collected packages: pyperclip
  Running setup.py bdist_wheel for pyperclip ... done
  Stored in directory: /root/.cache/pip/wheels/73/8c/77/a973e2fbf4808af077582b1740b4cbf9e100262da0166e90d8
Successfully built pyperclip
Installing collected packages: pyperclip, colorama, click, joblib, pycryptodome, anidbcli
Successfully installed anidbcli-1.22 click-6.7 colorama-0.3.9 joblib-0.12.2 pycryptodome-3.6.6 pyperclip-1.6.4

~# anidbcli
Traceback (most recent call last):
  File "/usr/local/bin/anidbcli", line 7, in <module>
    from anidbcli import main
  File "/usr/local/lib/python2.7/dist-packages/anidbcli/__init__.py", line 1, in <module>
    from .anidbconnector import AnidbConnector
  File "/usr/local/lib/python2.7/dist-packages/anidbcli/anidbconnector.py", line 4, in <module>
    import anidbcli.encryptors as encryptors
  File "/usr/local/lib/python2.7/dist-packages/anidbcli/encryptors.py", line 1, in <module>
    from abc import ABC, abstractmethod
ImportError: cannot import name ABC
```
What are the exact dependencies for running the tool? OS is Debian 9.5 amd64.

**Comment by kobuki** [comment]
Anidbcli seems to require Python 3.5+. In pyenv with 3.6.6 it works without problems.

**Comment by adameste** [comment]
Did not receive e-mail notifications about issues somehow. Issue resolved and added requirements section to main page.
